// eslint-disable-next-line import/no-anonymous-default-export
export default {
  key: "french_rounded",
  name: "Font.`",
  description: "Font, rounded below 6a. E.g. 4-, 4 and 4+.",
  types: ["boulder"],
  data: [
    { value: 2, name: "2" },
    { value: 2.5, name: "2" },
    { value: 2.75, name: "2+" },
    { value: 3, name: "3" },
    { value: 3.33, name: "3+" },
    { value: 3.67, name: "4-" },
    { value: 4, name: "4" },
    { value: 4.33, name: "4+" },
    { value: 4.67, name: "5-" },
    { value: 5, name: "5" },
    { value: 5.5, name: "5+" },
    { value: 6, name: "6A" },
    { value: 6.17, name: "6A+" },
    { value: 6.33, name: "6B" },
    { value: 6.5, name: "6B+" },
    { value: 6.67, name: "6C" },
    { value: 6.83, name: "6C+" },
    { value: 7, name: "7A" },
    { value: 7.17, name: "7A+" },
    { value: 7.33, name: "7B" },
    { value: 7.5, name: "7B+" },
    { value: 7.67, name: "7C" },
    { value: 7.83, name: "7C+" },
    { value: 8, name: "8A" },
    { value: 8.17, name: "8A+" },
    { value: 8.33, name: "8B" },
    { value: 8.5, name: "8B+" },
    { value: 8.67, name: "8C" },
    { value: 8.83, name: "8C+" },
    { value: 9, name: "9A" },
    { value: 9.17, name: "9A+" },
    { value: 9.33, name: "9B" },
    { value: 9.5, name: "9B+" },
  ],
};
