// eslint-disable-next-line import/no-anonymous-default-export
export default {
  key: "v_grade",
  name: "V-scale",
  description: "Hueco Vermin bouldering grade system",
  types: ["boulder"],
  data: [
    { value: 2, name: "VB" },
    { value: 3, name: "VB" },
    { value: 3.5, name: "V0-" },
    { value: 4, name: "V0" },
    { value: 4.5, name: "V0+" },
    { value: 5, name: "V1" },
    { value: 5.5, name: "V2" },
    { value: 6, name: "V3" },
    { value: 6.33, name: "V4" },
    { value: 6.67, name: "V5" },
    { value: 7, name: "V6" },
    { value: 7.2, name: "V7" },
    { value: 7.4, name: "V8" },
    { value: 7.6, name: "V9" },
    { value: 7.8, name: "V10" },
    { value: 8, name: "V11" },
    { value: 8.17, name: "V12" },
    { value: 8.33, name: "V13" },
    { value: 8.5, name: "V14" },
    { value: 8.67, name: "V15" },
    { value: 8.83, name: "V16" },
    { value: 9, name: "V17" },
  ],
};
